version: 2
sources:
- name: import
  schema: import
  tables:
  - name: customers
    identifier: customers
  - name: products
    identifier: products
  - name: resellers
    identifier: resellers
  - name: transactions
    identifier: transactions
  - name: channels
    identifier: channels
- name: preprocessed
  schema: staging
  tables:
  - name: resellerxmlextracted
    identifier: resellerxmlextracted